name: Post Publish
on:
  workflow_dispatch:
    inputs:
      release-tag:
        type: string
        description: 'Semver release tag e.g. v1.1.0'
        required: true
jobs:
  tidy-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Tidy Jira
        uses: breathingdust/github-jira-tidy@v0.3.0
        with:
          jira_host: ${{ secrets.jira_host }}
          jira_username: ${{ secrets.jira_username }}
          jira_password: ${{ secrets.jira_password }}
          jira_jql_filter: ${{ secrets.jira_jql_filter }}
          jira_closed_id: ${{ secrets.jira_closed_id }}
          jira_github_url_field_id: ${{ secrets.jira_github_url_field_id }}
          github_release_name: ${{ github.event.inputs.release-tag }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
